plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'java'
    id 'org.beryx.jlink' version '2.25.0'
    id 'org.javamodularity.moduleplugin' version '1.8.12'
}

group 'org'

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'org.openjfx:javafx-controls:17'
    implementation 'org.openjfx:javafx-fxml:17'
    implementation 'org.openjfx:javafx-graphics:17'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'org.postgresql:postgresql:42.7.2'
}

javafx {
    version = "21.0.1"
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.graphics' ]
}


test {
    useJUnitPlatform()
}

run {
    mainClass = 'main.java.org.Main'
    standardInput = System.in
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}

application {
    mainClass = 'main.java.org.Main'
}

jlink {
    imageZip = project.file("${buildDir}/distributions/app-${javafx.platform.classifier}.zip")
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'app'
    }
}

jlinkZip {
    group = 'distribution'
}